"""
Evaluation-only agent for OBELIX.
Compatible with Dueling DQN weights generated by train_d3qn_per_gemini.py.
"""

from __future__ import annotations
from typing import List, Optional
import os
import numpy as np
import torch
import torch.nn as nn

ACTIONS: List[str] = ["L45", "L22", "FW", "R22", "R45"]

class DuelingDQN(nn.Module):
    def __init__(self, in_dim: int = 18, n_actions: int = 5, hidden_dim: int = 128):
        super().__init__()
        # Matches the architecture in the training script
        self.feature = nn.Sequential(
            nn.Linear(in_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
        )
        self.value = nn.Sequential(
            nn.Linear(hidden_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 1),
        )
        self.adv = nn.Sequential(
            nn.Linear(hidden_dim, 64),
            nn.ReLU(),
            nn.Linear(64, n_actions),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        f = self.feature(x)
        v, a = self.value(f), self.adv(f)
        # Q(s,a) = V(s) + (A(s,a) - mean(A(s,a)))
        return v + (a - a.mean(dim=-1, keepdim=True))

# Global state for evaluation
_model: Optional[DuelingDQN] = None
_last_action: Optional[int] = None
_repeat_count: int = 0

# Smoothing Hyperparameters
_MAX_REPEAT = 2
_CLOSE_Q_DELTA = 0.05

def _load_once():
    global _model
    if _model is not None:
        return
    
    here = os.path.dirname(__file__)
    wpath = os.path.join(here, "weights.pth")
    
    if not os.path.exists(wpath):
        raise FileNotFoundError(f"weights.pth not found at {wpath}. Train first!")
    
    # Initialize with the same hidden_dim used in training
    m = DuelingDQN(hidden_dim=128)
    
    # Load weights (map to CPU since we are in evaluation mode)
    sd = torch.load(wpath, map_location="cpu")
    
    # Handle cases where the full checkpoint is saved instead of just state_dict
    if isinstance(sd, dict) and "state_dict" in sd:
        sd = sd["state_dict"]
        
    m.load_state_dict(sd)
    m.eval()
    _model = m

@torch.no_grad()
def policy(obs: np.ndarray, rng: np.random.Generator) -> str:
    global _last_action, _repeat_count
    _load_once()
    
    # Convert observation to tensor
    x = torch.tensor(obs, dtype=torch.float32).unsqueeze(0)
    q = _model(x).squeeze(0).numpy()
    best = int(np.argmax(q))

    # Action Smoothing logic to prevent rapid oscillation
    if _last_action is not None:
        order = np.argsort(-q)
        best_q, second_q = float(q[order[0]]), float(q[order[1]])
        
        # If the top two actions are very close, stick with the previous action
        if (best_q - second_q) < _CLOSE_Q_DELTA:
            if _repeat_count < _MAX_REPEAT:
                best = _last_action
                _repeat_count += 1
            else:
                _repeat_count = 0
        else:
            _repeat_count = 0

    _last_action = best
    return ACTIONS[best]